sudo: required

dist: stretch

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_script:
  - pip install docutils
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 law || exit $?
  - python -m unittest tests
