language: python
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      python: "2.7"
    - os: linux
      dist: trusty
      python: "3.5"

install: pip install -r requirements.txt

script: python -m unittest tests
