sudo: required

dist: stretch

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

before_install:
  - pip install docutils
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 law || exit $?
  - python -m unittest tests
